queue:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: true


- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'

    includeRootFolder: false


- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'


- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy: rs-pipeline'
  inputs:
    azureSubscription: 'Architecture Playground (4371fb0e-3c13-40da-9b2d-37d09cc60a86)'

    appType: applinux

    WebAppName: 'rs-pipeline'

    ImageSource: Builtin

    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'

    RuntimeStack: 'NODE|10.10'

